# Generated by Django 4.2.7 on 2023-11-30 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("short_description", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("grid_image", models.ImageField(upload_to="project_images/")),
                ("hero_image", models.ImageField(upload_to="")),
                ("project_link", models.URLField()),
                ("github_link", models.URLField()),
                ("blog_post", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="project_language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="project_language_mapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.project_language",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_mappings",
                        to="main.project",
                    ),
                ),
            ],
        ),
    ]
