# Generated by Django 4.2.7 on 2023-11-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="blog_post",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="grid_image",
            field=models.ImageField(null=True, upload_to="project_images/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="hero_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
