# Generated by Django 4.2.7 on 2023-11-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_project_blog_post_alter_project_github_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="grid_image",
            field=models.ImageField(blank=True, null=True, upload_to="project_images/"),
        ),
    ]
