# Generated by Django 4.2.7 on 2023-12-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_project_grid_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="grid_image",
            field=models.ImageField(blank=True, null=True, upload_to="admin/images/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="hero_image",
            field=models.ImageField(blank=True, null=True, upload_to="admin/images/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="project_language",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="project_language_mapping",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
